# Description: Configuration file for test
# 
N_E: 800
N_I: 200
P_EE: 0.1
P_EI: 0.1
P_IE: 0.05
P_II: 0.4
RandomStrength : 1
factor_mn: 1 # scaling factor fßor the mean of W_rank1
taud_E: 2
taud_I: 5
# taud_E:
#  - 2
#  - 100
# taud_I:
#  - 5
#  - 100
# ratio_fast: 0.2 # ratio of fast synapses

num_phase: 9 # number of phases to test
trails: 1 # number of trails

# eta_E: 0.1 # average bias input to E (lorentzian distribution)
# eta_I: 0.2
eta_E: 2 # average bias input to E (lorentzian distribution)
eta_I: 3
delta_E: 0.04 # variance of bias input to E (lorentzian distribution)
delta_I: 0.04

mu: 0
sigma: 0.2
sigma_rand: 0.1   # 100/(N_E+N_I)


dt: 0.1 #(ms/step)
T_pre: 200 # length of time before sti (ms)
T_sti: 10 # length of time for sti (ms)
T_after: 290 # length of time after sti (ms)

InputStrength: 10 #Input Strength (maybe chage to norm in the future)
#5，4，3，2

# norm_input: 1 # Normalization of input
color_Go: '#1C63A9'
color_Nogo: '#009999'